name: Tests

on: push

env:
  ARTIFACT_EXECUTABLE: itaxotools-blast-gui-windows


jobs:

  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Get BLAST+ binaries
        run: python tools/get_blast_binaries.py

      - name: Test with pytest
        run: |
          pip install pytest
          pytest


  build-executable:
    name: Build Windows executable
    runs-on: windows-2019
    needs:
      - test

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Get BLAST+ binaries
        run: python tools/get_blast_binaries.py

      - name: Make executable
        run: pyinstaller gui.spec

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_EXECUTABLE }}
          path: dist/*.exe
