name: Windows-Merge

on: workflow_dispatch
# on: push

env:
  ARTIFACT_EXECUTABLE: itaxotools-blast-gui-merge-windows


jobs:

  build-executable:
    name: Build Windows executable (merge task only)
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Set environment variable
        run: echo "BLASTAX_MERGE=true" >> $GITHUB_ENV

      - name: Make executable
        uses: iTaxoTools/TaxIGui/.github/actions/make-executable@main

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_EXECUTABLE }}
          path: dist/*.exe
